### ISSUE TITLE
This is not an hashmap but a https://en.wikipedia.org/wiki/M-ary_tree

### ISSUE THREAD

**Issue by RoyBellingan** [rohanrhu/libhash#1]
!

**Comment by rohanrhu** [comment]
Yes... I always invent things and hope that they were not invented before lol. I thought without hashing and using smart keys might be more efficient but idk.

I just added hashing feature (https://github.com/rohanrhu/libhash/commit/e8c860053141922e3ecff6cc232d27e39fb49914) and **keys are now fixed to 4 bytes**. I wrote the hash function quickly almost in a coffee break so not sure how decent it is but it looked working oki.
